[project]
name = "runpod-repro"
version = "0.1.0"
description = "Add a short description here"
authors = ["sigma-andex <77549848+sigma-andex@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64","linux-64"]


[tasks]
handler = "python -m saliency.handler --rp_serve_api"

[dependencies]
python = ">=3.12.4,<3.13"

# [pypi-options]
# # These are sections specifically related to the PyPI configuration.
# extra-index-urls = []

[pypi-dependencies]
transformers = ">=4.55.4"
accelerate = ">=1.6.0, <2"
numpy = ">=1.26.4, <2"
pydantic = ">=2.8.2,<2.9"
fastapi = ">=0.111.0"
absl-py = ">=2.1.0,<2.2"
huggingface-hub = ">=0.34.4"
pytest = "*"
sentencepiece = ">=0.2.0, <0.3"
pyhamcrest = ">=2.1.0, <2.2"
runpod = ">=1.7.13, <1.8"
torch = ">=2.8.0"
torch-vision = ">=0.1.6.dev0, <0.2"
captum = ">=0.8.0"
hf-xet = ">=1.1.7, <2"
torchvision = ">=0.23.0, <0.24"


